name: wizard
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Getx Extralight statemanager,++ package
  get: ^4.1.4
  palette_generator: ^0.3.0
  auto_size_text: ^2.1.0

  firebase_core: ^1.4.0
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1

  file_picker: ^3.0.4
  image_picker: ^0.8.2
  just_audio: ^0.9.5
  audio_service: ^0.17.1
  # audio_video_progress_bar: ^0.4.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  flutter_charts: ^0.2.0
  cached_network_image: ^3.1.0
  
  google_fonts: ^2.1.0
  get_storage:

  # //NOTIFICATIONS FIREBASE
  firebase_messaging: ^10.0.4
  # //LOCAIS
  flutter_local_notifications: ^8.1.1+1
  badges: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      
      - assets/images/wizard_pics/
      - assets/images/other/
      - assets/images/
      - assets/musics/
      - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
          style: normal
    # - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
    - family: Fuggles
      fonts:
        - asset: assets/fonts/Fuggles/Fuggles-Regular.ttf
    - family: HoneySc
      fonts:
        - asset: assets/fonts/honey_script_font_6576/HoneyScript-Light.ttf
        - asset: assets/fonts/honey_script_font_6576/HoneyScript-SemiBold.ttf
      
    - family: Brush
      fonts:
        - asset: assets/fonts/brush/brush.ttf
        # - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
        # - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
        # - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        #   style: normal
          # weight: 700
    - family: DancingScript
      fonts :
        - asset: assets/fonts/dancing-script-ot/DancingScript-Regular.otf
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento/Sacramento-Regular.ttf
        # - asset: assets/fonts/Ubuntu/Ubuntu-Italic.ttf
        # - asset: assets/fonts/Ubuntu/Ubuntu-Medium.ttf
        # - asset: assets/fonts/Ubuntu/Ubuntu-Bold.ttf
        #   style: normal
          # weight: 700
    - family: Righteous
      fonts :
        - asset: assets/fonts/Righteous/Righteous-Regular.ttf
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
